#!/usr/bin/env python

from __future__ import print_function
from sunlight import influenceexplorer

contrib = influenceexplorer.contributions(
    contributor_state="md|va",
    recipient_ft="mikulski",
    cycle="2008" )

for contributor in contrib:
    print( "%s from %s contributed %s" % (
        contributor['contributor_name'],
        contributor['contributor_city'],
        contributor['amount']
    ))
