#!/usr/bin/env python

from __future__ import print_function
from sunlight import influenceexplorer

contracts = influenceexplorer.contracts(
    vendor_name="Microsoft"
)

for contract in contracts:
    print( "%s contract for at least %s to %s" % (
        contract['transaction_status'],
        contract['obligatedamount'],
        contract['descriptionofcontractrequirement']
    ))
