#!/usr/bin/env python

from sunlight import capitolwords

for phrase in capitolwords.phrases( "month", "201007", sort="count+desc" ):
    print "%s was used %s times" % ( phrase['ngram'], phrase['count'] )
