#!/usr/bin/env python

from sunlight import capitolwords

for person in capitolwords.phrases_by_entity(
    "legislator",
    phrase="free market",
    sort="count",
):
    print "Congress BioGuide ID: %s" % person['legislator']
