#!/usr/bin/env python

from sunlight import capitolwords

for phrase in capitolwords.text( phrase="obama administration" )['results']:
    print "%s mentions Obama on %s" % ( phrase['title'], phrase['date'] )
