#!/usr/bin/env python

from __future__ import print_function
from sunlight import capitolwords

for phrase in capitolwords.text( phrase="obama administration" ):
    print( "%s mentions Obama on %s" % ( phrase['title'], phrase['date'] ))
