#!/usr/bin/env python

from __future__ import print_function
from sunlight import congress

nancy = congress.legislators( lastname="Pelosi" )[0]
print( "%s %s %s (%s)" % ( nancy['title'], nancy['firstname'],
    nancy['lastname'], nancy['party'] ))
