#!/usr/bin/env python

from sunlight import congress

nancy = congress.legislators( lastname="Pelosi" )[0]
print "%s %s %s (%s)" % ( nancy['title'], nancy['firstname'],
    nancy['lastname'], nancy['party'] )
