#!/usr/bin/env python
# Copyright (c) 2012 Paul Tagliamonte <paultag@sunlightfoundation.com>
# under the terms of the LICENSE file

from sunlight import openstates

bill = openstates.bill_detail( 'ca', '20092010', 'AB 667')
print "%s - %s" % ( bill['bill_id'], bill['+short_title'] )
