#!/usr/bin/env python
# Copyright (c) 2012 Paul Tagliamonte <paultag@sunlightfoundation.com>
# under the terms of the LICENSE file

from sunlight import openstates

reps = openstates.legislator_geo_search(
    longitude="-78.76648",
    latitude="35.81336"
)
for rep in reps:
    print "%s - %s %s" % ( rep['chamber'], rep['first_name'], rep['last_name'] )
