#!/usr/bin/env python
# Copyright (c) 2012 Paul Tagliamonte <paultag@sunlightfoundation.com>
# under the terms of the LICENSE file

from sunlight import openstates

ctty = openstates.committee_detail( "MDC000065" )
print "%s is the %s" % ( ctty['id'], ctty['committee'] )
