#!/usr/bin/env python
# Copyright (c) 2012 Paul Tagliamonte <paultag@sunlightfoundation.com>
# under the terms of the Expat license.

from sunlight import OpenStates
os = OpenStates()

vt_agro_bills = os.bills(
    q='agriculture',
        state='vt',
            chamber='upper'
            )

for bill in vt_agro_bills:
        print bill['title']
